fieldLayouts:
  fcf1f589-32ab-422d-8ff7-b4f22a73e664:
    tabs:
      -
        fields:
          b5b5edb5-b62f-41c2-a7ed-89e2b72e1c58:
            required: false
            sortOrder: 1
        name: Main
        sortOrder: 1
handle: services
name: Services
siteSettings:
  8e487d70-7966-4e1f-a6dd-bfbbb1dd9100:
    hasUrls: true
    template: work/index
    uriFormat: 'work/service/{slug}'
structure:
  maxLevels: null
  uid: fc5b02e8-6367-450b-84a1-45b214a20262
