contentColumnType: string
fieldGroup: 3690a445-5c74-47c8-a37d-af19533bfdcf
handle: altImage
instructions: 'Used for thumbnail in list views, second image is shown on hover'
name: 'Thumbnail Images'
searchable: true
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:d0e9262d-3cc0-46bc-aa1c-76d99cb9f385'
  defaultUploadLocationSubpath: '{slug}'
  limit: '2'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: 'Set thumbnail images'
  singleUploadLocationSource: 'volume:d0e9262d-3cc0-46bc-aa1c-76d99cb9f385'
  singleUploadLocationSubpath: '{slug}'
  source: null
  sources:
    - 'volume:d0e9262d-3cc0-46bc-aa1c-76d99cb9f385'
  targetSiteId: null
  useSingleFolder: '1'
  validateRelatedElements: ''
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
