contentColumnType: text
fieldGroup: d2d1260a-da85-41ec-8e8a-c16e376cf34f
handle: captionLabel
instructions: ''
name: 'Caption Label'
searchable: true
settings:
  charLimit: '80'
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
