contentColumnType: text
fieldGroup: 9aec6670-8753-4f2e-91d5-03ff2b4f3ef6
handle: manualAuthor
instructions: 'Shown on single posts below title'
name: Author
searchable: true
settings:
  charLimit: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
