contentColumnType: string
fieldGroup: 7d6b2f37-d8cf-429f-8b3f-f3d7df5d814b
handle: photo
instructions: ''
name: Photo
searchable: true
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:cd389634-6297-4886-ac1a-17f7ff2050c8'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: 'Select photo'
  singleUploadLocationSource: 'volume:cd389634-6297-4886-ac1a-17f7ff2050c8'
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: '1'
  validateRelatedElements: ''
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
