contentColumnType: string
fieldGroup: 7d6b2f37-d8cf-429f-8b3f-f3d7df5d814b
handle: pronouns
instructions: ''
name: Pronouns
searchable: true
settings:
  charLimit: ''
  code: ''
  columnType: string
  initialRows: '4'
  multiline: ''
  placeholder: 'e.g. she / her / hers'
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
