contentColumnType: string
fieldGroup: 9ace857e-959b-4a74-b0e0-42873080c846
handle: seoDescription
instructions: 'Used for meta description to improve SEO'
name: 'SEO Description'
searchable: true
settings:
  charLimit: '155'
  code: ''
  columnType: string
  initialRows: '2'
  multiline: '1'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
