contentColumnType: string
fieldGroup: 9ace857e-959b-4a74-b0e0-42873080c846
handle: seoImage
instructions: 'Used when sharing a post or page on social'
name: 'SEO Image'
searchable: true
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:42068817-6f6f-4a12-8420-4c2bf823fa58'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: 'Add an image'
  singleUploadLocationSource: 'volume:42068817-6f6f-4a12-8420-4c2bf823fa58'
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: ''
  validateRelatedElements: ''
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
