contentColumnType: string
fieldGroup: 9aec6670-8753-4f2e-91d5-03ff2b4f3ef6
handle: shareImage
instructions: 'Default share image used for pages with no inherent shareable image'
name: 'Global Share Image'
searchable: true
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:42068817-6f6f-4a12-8420-4c2bf823fa58'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: ''
  singleUploadLocationSource: 'volume:42068817-6f6f-4a12-8420-4c2bf823fa58'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:42068817-6f6f-4a12-8420-4c2bf823fa58'
  targetSiteId: null
  useSingleFolder: ''
  validateRelatedElements: ''
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
