field: 216d4589-17fe-484e-9a60-707a9dc09536
fieldLayouts:
  46e78fb9-98d5-474c-97b5-1378e6c6a3db:
    tabs:
      -
        fields:
          30ff7126-9c3b-45f8-8bd7-53139d5c28cd:
            required: false
            sortOrder: 2
          d7f5bbc1-0a3b-44c9-b389-3722daa0d2f8:
            required: false
            sortOrder: 3
          ff17b8dd-04eb-43b7-b2e2-3f73a408f503:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  30ff7126-9c3b-45f8-8bd7-53139d5c28cd:
    contentColumnType: string
    fieldGroup: null
    handle: mainImage
    instructions: ''
    name: 'Main Image'
    searchable: true
    settings:
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:42068817-6f6f-4a12-8420-4c2bf823fa58'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: 'Select main image'
      singleUploadLocationSource: 'volume:42068817-6f6f-4a12-8420-4c2bf823fa58'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: ''
      validateRelatedElements: ''
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  d7f5bbc1-0a3b-44c9-b389-3722daa0d2f8:
    contentColumnType: string
    fieldGroup: null
    handle: secondaryImage
    instructions: ''
    name: 'Secondary Image'
    searchable: true
    settings:
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:42068817-6f6f-4a12-8420-4c2bf823fa58'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: 'Select secondary image'
      singleUploadLocationSource: 'volume:42068817-6f6f-4a12-8420-4c2bf823fa58'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: ''
      validateRelatedElements: ''
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  ff17b8dd-04eb-43b7-b2e2-3f73a408f503:
    contentColumnType: string
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: string
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
