field: 9cca299e-1dbc-4979-90fc-f41d2bbb1937
fieldLayouts:
  1904a232-23d3-483a-a31d-31d8b3c0e48c:
    tabs:
      -
        fields:
          12d191c1-4cf6-4a3e-be8f-bed2806425f8:
            required: false
            sortOrder: 1
          ccc6bfde-ea63-4c3a-b1ab-62fa533a9d93:
            required: false
            sortOrder: 2
        name: Content
        sortOrder: 1
fields:
  12d191c1-4cf6-4a3e-be8f-bed2806425f8:
    contentColumnType: text
    fieldGroup: null
    handle: intro
    instructions: ''
    name: Intro
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '2'
      multiline: '1'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ccc6bfde-ea63-4c3a-b1ab-62fa533a9d93:
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: ''
    name: Description
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Standard.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
