field: a2483d09-6798-40be-8f35-c45413ed2e03
fieldLayouts:
  b3de5b92-cde3-4021-b389-da0218d168b1:
    tabs:
      -
        fields:
          195d4768-976a-455a-aede-a233cfa8b363:
            required: false
            sortOrder: 1
          a937d4b1-f5ba-42cf-8c90-a903d38ee8cc:
            required: false
            sortOrder: 2
        name: Content
        sortOrder: 1
fields:
  195d4768-976a-455a-aede-a233cfa8b363:
    contentColumnType: string
    fieldGroup: null
    handle: serviceName
    instructions: ''
    name: 'Service Name'
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: string
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a937d4b1-f5ba-42cf-8c90-a903d38ee8cc:
    contentColumnType: text
    fieldGroup: null
    handle: serviceDescription
    instructions: 'A short sentence or two describing the service'
    name: 'Service Description'
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '2'
      multiline: '1'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
