enableVersioning: true
handle: ideasIndex
name: 'Ideas Index'
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  8e487d70-7966-4e1f-a6dd-bfbbb1dd9100:
    enabledByDefault: true
    hasUrls: true
    template: ideas/index
    uriFormat: ideas
type: single
