enableVersioning: true
handle: work
name: Work
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  8e487d70-7966-4e1f-a6dd-bfbbb1dd9100:
    enabledByDefault: true
    hasUrls: true
    template: work/_entry
    uriFormat: 'work/{slug}'
structure:
  maxLevels: 1
  uid: 5daaae73-b639-4c0c-8985-9d6cec55df31
type: structure
